# Generated by Django 3.2.6 on 2022-08-05 18:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_subdistributors'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningStockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('addedAt', models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 5, 19, 44, 21, 653365))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.products')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('addedAt', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.products')),
            ],
        ),
    ]
