# Generated by Django 3.2.6 on 2022-08-05 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_openingstock_openingstockhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingstock',
            name='addedAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='openingstockhistory',
            name='addedAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
