# Generated by Django 3.2.6 on 2022-08-06 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20220805_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingstock',
            name='addedAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
