# Generated by Django 3.2.6 on 2022-08-06 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_auto_20220806_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closingstock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audit.products'),
        ),
        migrations.AlterField(
            model_name='closingstockhistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audit.products'),
        ),
        migrations.AlterField(
            model_name='newstock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audit.products'),
        ),
        migrations.AlterField(
            model_name='newstockhistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audit.products'),
        ),
        migrations.AlterField(
            model_name='openingstock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audit.products'),
        ),
        migrations.AlterField(
            model_name='openingstockhistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audit.products'),
        ),
    ]
