# Generated by Django 3.2.6 on 2022-08-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_auto_20220806_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingstockhistory',
            name='addedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
