# Generated by Django 3.2.6 on 2022-08-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_auto_20220809_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingstock',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='openingstockhistory',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
