# Generated by Django 3.2.6 on 2022-08-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0014_auto_20220809_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingstock',
            name='addedAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='openingstockhistory',
            name='addedAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
