# Generated by Django 3.2.6 on 2022-08-10 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0015_auto_20220810_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstock',
            name='addedAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='newstockhistory',
            name='addedAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='openingstock',
            name='addedAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='openingstockhistory',
            name='addedAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
