# Generated by Django 3.2.6 on 2022-08-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0017_wholesalerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closingstock',
            name='addedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='closingstockhistory',
            name='addedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newstock',
            name='addedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newstockhistory',
            name='addedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='openingstock',
            name='addedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='openingstockhistory',
            name='addedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
