# Generated by Django 3.2.6 on 2022-08-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0020_retailrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailrecord',
            name='productPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
