# Generated by Django 3.2.6 on 2022-08-15 18:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0021_retailrecord_productprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('productQuantity', models.IntegerField()),
                ('productPrice', models.FloatField()),
                ('soldAt', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.products')),
                ('subName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.subdistributors')),
            ],
        ),
    ]
