# Generated by Django 3.2.6 on 2022-08-15 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0022_subrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subrecord',
            old_name='subName',
            new_name='sub',
        ),
    ]
