# Generated by Django 3.2.6 on 2022-08-15 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0023_rename_subname_subrecord_sub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subrecord',
            old_name='sub',
            new_name='subName',
        ),
    ]
