# Generated by Django 3.2.6 on 2022-08-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0026_rename_products_shopdeliveryrecord_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdeliveryrecord',
            name='productBroughtBack',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
