# Generated by Django 3.2.6 on 2022-08-21 17:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0027_shopdeliveryrecord_productbroughtback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDeliveryRecordHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('driverName', models.CharField(max_length=100)),
                ('productQuantity', models.IntegerField()),
                ('productPrice', models.FloatField()),
                ('amountBroughtBack', models.FloatField(blank=True, default=0)),
                ('productBroughtBack', models.IntegerField(blank=True, default=0)),
                ('leftAt', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.products')),
            ],
        ),
    ]
