# Generated by Django 3.2.6 on 2022-08-30 22:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0028_shopdeliveryrecordhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDeliveryStartRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('productTakenQuantity', models.IntegerField()),
                ('productQuantityBroughtBack', models.IntegerField(blank=True, default=0)),
                ('amountBroughtBack', models.FloatField(blank=True, default=0)),
                ('leftAt', models.DateTimeField(auto_now_add=True)),
                ('productTaken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.products')),
            ],
        ),
    ]
