# Generated by Django 3.2.6 on 2022-09-01 10:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0030_activedeliverysalesrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activedeliverystartrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
