# Generated by Django 3.2.6 on 2022-09-01 10:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0031_alter_activedeliverystartrecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activedeliverystartrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
