# Generated by Django 3.2.6 on 2022-09-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0033_alter_activedeliverysalesrecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activedeliverysalesrecord',
            name='amtFromCustomer',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='activedeliverysalesrecord',
            name='customerCredit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='activedeliverysalesrecord',
            name='customerDebt',
            field=models.FloatField(default=0),
        ),
    ]
