# Generated by Django 3.2.6 on 2022-09-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0035_activedeliverystartrecord_salesid'),
    ]

    operations = [
        migrations.AddField(
            model_name='activedeliverysalesrecord',
            name='salesId',
            field=models.FloatField(default=0),
        ),
    ]
