# Generated by Django 3.2.6 on 2022-09-01 14:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0036_activedeliverysalesrecord_salesid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayDeliverySalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesId', models.FloatField(default=0)),
                ('deliveryCustName', models.CharField(max_length=100)),
                ('deliveryProductData', models.JSONField()),
                ('productValue', models.FloatField()),
                ('modeOfPayment', models.CharField(max_length=100)),
                ('amtFromCustomer', models.FloatField(default=0)),
                ('customerDebt', models.FloatField(default=0)),
                ('customerCredit', models.FloatField(default=0)),
                ('purchasedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TodayDeliveryStartRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('salesId', models.FloatField(default=0)),
                ('productTakenQuantity', models.IntegerField()),
                ('productQuantityBroughtBack', models.IntegerField(blank=True, default=0)),
                ('amountBroughtBack', models.FloatField(blank=True, default=0)),
                ('leftAt', models.DateTimeField(auto_now_add=True)),
                ('productTaken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.products')),
            ],
        ),
    ]
