# Generated by Django 3.2.6 on 2022-09-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0040_auto_20220902_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closingstockhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newstockhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='openingstockhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
