# Generated by Django 3.2.6 on 2022-10-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0047_alter_wholesalerecord_productsdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subrecord',
            name='product',
        ),
        migrations.RemoveField(
            model_name='subrecord',
            name='productPrice',
        ),
        migrations.RemoveField(
            model_name='subrecord',
            name='productQuantity',
        ),
        migrations.AddField(
            model_name='subrecord',
            name='amtFromSubDistributor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subrecord',
            name='modeOfPayment',
            field=models.CharField(default='Cash', max_length=100),
        ),
        migrations.AddField(
            model_name='subrecord',
            name='productData',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='subrecord',
            name='productValue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subrecord',
            name='subDistributorCredit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subrecord',
            name='subDistributorDebt',
            field=models.FloatField(default=0),
        ),
    ]
