# Generated by Django 3.2.6 on 2022-10-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0049_todaytauditid_totalaudit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='todayTauditId',
        ),
        migrations.DeleteModel(
            name='TotalAudit',
        ),
    ]
