# Generated by Django 3.2.6 on 2022-10-09 11:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0051_todaytauditid_totalaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalaudit',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
