# Generated by Django 3.2.6 on 2022-10-09 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0052_alter_totalaudit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalaudit',
            name='driver',
            field=models.ForeignKey(default='Driver Name not set', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivername', to='audit.profile'),
        ),
        migrations.AlterField(
            model_name='totalaudit',
            name='shopAttendant',
            field=models.ForeignKey(default='Shop Attendant name not Set', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopattendantname', to='audit.profile'),
        ),
    ]
