# Generated by Django 3.2.6 on 2022-10-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0053_auto_20221009_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopdeliveryrecord',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shopdeliveryrecord',
            name='productPrice',
        ),
        migrations.RemoveField(
            model_name='shopdeliveryrecord',
            name='productQuantity',
        ),
        migrations.AddField(
            model_name='shopdeliveryrecord',
            name='productData',
            field=models.JSONField(default=dict),
        ),
    ]
