# Generated by Django 3.2.6 on 2022-10-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0054_auto_20221009_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdeliveryrecord',
            name='deliveryStatus',
            field=models.CharField(default='delivering', max_length=100),
        ),
    ]
