# Generated by Django 3.2.6 on 2022-10-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0055_shopdeliveryrecord_deliverystatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopDeliveryRecordHistory',
        ),
    ]
