# Generated by Django 3.2.6 on 2022-10-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0057_remove_shopdeliveryrecord_productbroughtback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todaydeliverystartrecord',
            name='productQuantityBroughtBack',
        ),
        migrations.RemoveField(
            model_name='todaydeliverystartrecord',
            name='productTaken',
        ),
        migrations.RemoveField(
            model_name='todaydeliverystartrecord',
            name='productTakenQuantity',
        ),
        migrations.AddField(
            model_name='todaydeliverysalesrecord',
            name='deliveryNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todaydeliverystartrecord',
            name='deliveryNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todaydeliverystartrecord',
            name='productsData',
            field=models.JSONField(default=dict),
        ),
    ]
