# Generated by Django 3.2.6 on 2022-10-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0058_auto_20221010_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todaydeliverysalesrecord',
            old_name='deliveryProductData',
            new_name='allCustomerData',
        ),
        migrations.RenameField(
            model_name='todaydeliverysalesrecord',
            old_name='purchasedAt',
            new_name='finishedAt',
        ),
        migrations.RenameField(
            model_name='todaydeliverystartrecord',
            old_name='leftAt',
            new_name='finishedAt',
        ),
        migrations.RemoveField(
            model_name='todaydeliverysalesrecord',
            name='amtFromCustomer',
        ),
        migrations.RemoveField(
            model_name='todaydeliverysalesrecord',
            name='customerCredit',
        ),
        migrations.RemoveField(
            model_name='todaydeliverysalesrecord',
            name='customerDebt',
        ),
        migrations.RemoveField(
            model_name='todaydeliverysalesrecord',
            name='modeOfPayment',
        ),
        migrations.RemoveField(
            model_name='todaydeliverysalesrecord',
            name='productValue',
        ),
    ]
