# Generated by Django 3.2.6 on 2022-10-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0059_auto_20221011_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todaydeliverysalesrecord',
            name='deliveryCustName',
        ),
    ]
