# Generated by Django 3.2.6 on 2022-10-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0060_remove_todaydeliverysalesrecord_deliverycustname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closingstockhistory',
            name='addedAt',
        ),
        migrations.RemoveField(
            model_name='closingstockhistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='closingstockhistory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='newstockhistory',
            name='addedAt',
        ),
        migrations.RemoveField(
            model_name='newstockhistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='newstockhistory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='openingstockhistory',
            name='addedAt',
        ),
        migrations.RemoveField(
            model_name='openingstockhistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='openingstockhistory',
            name='quantity',
        ),
        migrations.AddField(
            model_name='closingstockhistory',
            name='productsData',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='newstockhistory',
            name='productsData',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='openingstockhistory',
            name='productsData',
            field=models.JSONField(default=dict),
        ),
    ]
