# Generated by Django 3.2.6 on 2022-10-20 08:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0061_auto_20221012_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('message_type', models.CharField(max_length=100)),
                ('message_content', models.JSONField(default=dict)),
                ('message_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='totalaudit',
            name='customersCredit',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='totalaudit',
            name='customersInDebt',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='TodayInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('invoiceNumber', models.CharField(max_length=100)),
                ('invoiceImage', models.ImageField(upload_to='')),
                ('addedAt', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit.company')),
            ],
        ),
    ]
