# Generated by Django 3.2.6 on 2022-10-20 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0062_auto_20221020_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayInvoiceNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('invoiceNumber', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='TodayInvoice',
        ),
    ]
