# Generated by Django 3.2.6 on 2022-10-20 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0063_auto_20221020_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalaudit',
            old_name='invoiceIds',
            new_name='invoiceNumbers',
        ),
    ]
