# Generated by Django 3.2.6 on 2022-10-20 08:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0064_rename_invoiceids_totalaudit_invoicenumbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('totalAuditId', models.FloatField()),
                ('openingStock', models.JSONField(default=dict)),
                ('newStock', models.JSONField(default=dict)),
                ('closingStock', models.JSONField(default=dict)),
                ('driverDeliveryStockDetails', models.JSONField(default=dict)),
                ('shopAttendantDeliveryStockDetails', models.JSONField(default=dict)),
                ('expectedDriverDeliveryStockDetails', models.JSONField(default=dict)),
                ('expectedShopAttendantDeliveryStockDetails', models.JSONField(default=dict)),
                ('deliveryCustomersToTransfer', models.JSONField(default=dict)),
                ('invoiceNumbers', models.JSONField(default=dict)),
                ('allSubSales', models.JSONField(default=dict)),
                ('allWholesales', models.JSONField(default=dict)),
                ('allRetailSales', models.JSONField(default=dict)),
                ('shopCustomersToTransfer', models.JSONField(default=dict)),
                ('shopHandover', models.FloatField(default=0)),
                ('TotalDeliveryHandover', models.FloatField(default=0)),
                ('fullShopSalesAudit', models.JSONField(default=dict)),
                ('customersInDebt', models.JSONField(default=dict)),
                ('customersCredit', models.JSONField(default=dict)),
                ('messages', models.JSONField(default=dict)),
                ('auditDate', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(default='Driver Name not set', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todaydrivername', to='audit.profile')),
                ('shopAttendant', models.ForeignKey(default='Shop Attendant name not Set', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todayshopattendantname', to='audit.profile')),
            ],
        ),
    ]
