# Generated by Django 3.2.6 on 2022-10-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0065_todayaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_content',
            field=models.CharField(max_length=1000),
        ),
    ]
