# Generated by Django 3.2.6 on 2022-10-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0066_alter_messages_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdeliveryrecord',
            name='deliveryNumber',
            field=models.FloatField(default=0),
        ),
    ]
