# Generated by Django 3.2.6 on 2022-10-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0067_shopdeliveryrecord_deliverynumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remmittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopSalesHandover', models.FloatField(default=0)),
                ('shopDeliveryHandover', models.FloatField(default=0)),
            ],
        ),
    ]
