# Generated by Django 3.2.6 on 2022-10-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0069_remmittance_remmittedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='todayaudit',
            name='driverStatus',
            field=models.CharField(default='Driver has not closed', max_length=100),
        ),
        migrations.AddField(
            model_name='todayaudit',
            name='shopAttendantStatus',
            field=models.CharField(default='Shop attendant has not closed', max_length=100),
        ),
        migrations.AddField(
            model_name='totalaudit',
            name='driverStatus',
            field=models.CharField(default='Driver has not closed', max_length=100),
        ),
        migrations.AddField(
            model_name='totalaudit',
            name='shopAttendantStatus',
            field=models.CharField(default='Shop attendant has not closed', max_length=100),
        ),
    ]
