# Generated by Django 3.2.6 on 2022-10-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0070_auto_20221022_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='todayaudit',
            name='fullDeliverySalesAudit',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='totalaudit',
            name='fullDeliverySalesAudit',
            field=models.JSONField(default=dict),
        ),
    ]
