# Generated by Django 3.2.6 on 2022-10-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0072_auto_20221023_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalaudit',
            name='driver',
            field=models.CharField(default='Driver Name not set', max_length=100),
        ),
        migrations.AlterField(
            model_name='totalaudit',
            name='shopAttendant',
            field=models.CharField(default='Shop Attendant name not Set', max_length=100),
        ),
    ]
