# Generated by Django 3.2.6 on 2022-10-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0073_auto_20221023_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todayaudit',
            name='totalAuditId',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='totalaudit',
            name='totalAuditId',
            field=models.FloatField(default=0.0),
        ),
    ]
