# Generated by Django 3.2.6 on 2023-01-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0075_catalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='company',
            field=models.CharField(max_length=100),
        ),
    ]
